/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package london_police;

import org.apache.beam.runners.direct.DirectOptions;
import org.apache.beam.runners.direct.DirectRunner;
import org.apache.beam.sdk.Pipeline;
import org.apache.beam.sdk.options.PipelineOptionsFactory;
import org.apache.beam.sdk.transforms.Create;
import org.apache.beam.sdk.transforms.DoFn;
import org.apache.beam.sdk.transforms.ParDo;
import org.apache.beam.sdk.values.PCollection;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static final Logger LOG = LoggerFactory.getLogger(App.class);
    public static String apiPoliceUrl = "https://data.police.uk/api";

    public static void main(String[] args) {
        DirectOptions options = PipelineOptionsFactory.create().as(DirectOptions.class);
        options.setRunner(DirectRunner.class);
        options.setBlockOnRun(true);
        options.setTargetParallelism(1);

        Pipeline p = Pipeline.create(options);

        PCollection<String> start = p.apply(Create.of(""));
        PCollection<ForceResponse> forces = start.apply(new ReadForces(App.apiPoliceUrl));
        PCollection<NeighbourhoodResponse> neighbourhoods = forces.apply(new ReadNeighbourhoods(App.apiPoliceUrl));

        neighbourhoods.apply("", ParDo.of(new DoFn<NeighbourhoodResponse, Void>() {
            private static final long serialVersionUID = 1L;

            @ProcessElement
            public void processElement(@Element NeighbourhoodResponse input) {
                LOG.info(String.format("%s ; %s", input.id, input.name));
            }
        }));

        p.run().waitUntilFinish();
    }
}
