/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zoopla;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.Map;
import org.apache.beam.runners.direct.DirectOptions;
import org.apache.beam.runners.direct.DirectRunner;
import org.apache.beam.sdk.Pipeline;
import org.apache.beam.sdk.options.PipelineOptionsFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import common.ApiReader;
import common.Elasticsearch;

public class App {
    private static final Logger LOG = LoggerFactory.getLogger(App.class);
    public static String apiZooplaUrl = "http://api.zoopla.co.uk/api/v1";
    public static String elasticSearchUrl = "http://localhost:9200";
    public static ApiReader apiReader = new ApiReader(10); // This will break idempotency of
    // transforms but since running within
    // same process it can still be safely
    // used.

    public static void main(String[] args) throws URISyntaxException, IOException {
        String keyZooplaApi = System.getenv("API_KEY_ZOOPLA");
        if (keyZooplaApi == null) {
            LOG.error("Env API_KEY_ZOOPLA must be set");
            return;
        }
        DirectOptions options = PipelineOptionsFactory.create().as(DirectOptions.class);
        options.setRunner(DirectRunner.class);
        options.setTargetParallelism(20);
        Pipeline p = Pipeline.create(options);
        Elasticsearch.deleteIndex("home_rentals", elasticSearchUrl);
        Elasticsearch.mapIndex("home_rentals", Map.ofEntries(Map.entry("location", "geo_point")),
                elasticSearchUrl);

        p.apply(new UpdateZooplaRentals(App.apiZooplaUrl, elasticSearchUrl, keyZooplaApi));
        p.run().waitUntilFinish();
    }
}
